on:
  workflow_call:
    inputs:
      codecov_token:
        required: false
        description: 'Codecov token'
        default: "bc15b944-6b42-420a-b3f9-a5a8fb214326"
        type: string
      ruby_version:
        description: 'Ruby Version'
        default: "3.2.2"
        required: false
        type: string
      working-directory:
        required: true
        type: string
      node_version:
        description: 'Node version'
        default: '18.17.1'
        required: false
        type: string
      test_command:
        description: 'The testing command to be ran'
        required: true
        type: string
      bullet_enabled:
        description: 'Enable bullet performance testing'
        required: false
        default: true
        type: boolean
      bullet_n_plus_one:
        description: 'Enable bullet n+1 testing'
        required: false
        default: true
        type: boolean
      bullet_counter_cache:
        description: 'Enable bullet counter cache testing'
        required: false
        default: true
        type: boolean
      bullet_unused_eager_loading:
        description: 'Enable bullet unused eager loading testing'
        required: false
        default: true
        type: boolean

jobs:
  build_app:
    name: Test app
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RUBYOPT: '-W:no-deprecated'
    services:
      validator:
        image: ghcr.io/validator/validator:latest
        ports: ["8888:8888"]
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: nanasess/setup-chromedriver@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: |
          bundle install
          bundle exec rake test_app
        name: Create test app
        shell: "bash"
      - run: mkdir -p ./spec/decidim_dummy_app/tmp/screenshots
        name: Create the screenshots folder
        shell: "bash"
      - run: |
          bundle install
          ls -lah
          bundle exec rails assets:precompile
          ls -lah
          bundle exec rake parallel:create parallel:load_schema
          ls -lah
        name: Parallel tests
        shell: "bash"
        working-directory: ./spec/decidim_dummy_app/
        env:
          NODE_ENV: "test"
          RAILS_ENV: "test"
      - run: |
          sudo Xvfb -ac $DISPLAY -screen 0 1920x1084x24 > /dev/null 2>&1 & # optional
          ls -lah
          bundle install
          ls -lah 
          ${{ inputs.test_command }}
        name: RSpec
        working-directory: ${{ inputs.working-directory }}
        env:
          VALIDATOR_HTML_URI: http://localhost:8888/
          RUBY_VERSION: ${{ inputs.ruby_version }}
          DECIDIM_MODULE: ${{ inputs.working-directory }}
          CODECOV_TOKEN: ${{ inputs.codecov_token }}
          DECIDIM_BULLET_ENABLED: ${{ inputs.bullet_enabled }}
          DECIDIM_BULLET_N_PLUS_ONE: ${{ inputs.bullet_n_plus_one }}
          DECIDIM_BULLET_COUNTER_CACHE: ${{ inputs.bullet_counter_cache }}
          DECIDIM_BULLET_UNUSED_EAGER: ${{ inputs.bullet_unused_eager_loading }}
          DISPLAY: ":99"
          CI: "true"
          SIMPLECOV: "true"
          SHAKAPACKER_RUNTIME_COMPILE: "false"
          NODE_ENV: "test"
      - uses: codecov/codecov-action@v3
        name: Upload coverage
        with:
          token: ${{ inputs.codecov_token }}
          name: ${{ inputs.working-directory }}
          flags: ${{ inputs.working-directory }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path:  /home/runner/.npm/_logs
          if-no-files-found: ignore
